apiVersion: v1
kind: ReplicationController
metadata:
  name: datalab-rc
  labels:
    server: prod
    app: datalab-rc
spec:
  replicas: 1
  selector:
    server: prod
    app: datalab
  template:
    metadata:
      labels:
        server: prod
        app: datalab
    spec:
      containers:
        - name: datalab
          image: gcr.io/cloud-datalab/datalab:local
          command: ['/datalab/run.sh']
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              hostPort: 8899
          env:
            - name: DATALAB_ENV
              value: GCE
          volumeMounts:
            - name: home
              mountPath: /content
        - name: logger
          image: gcr.io/google_containers/fluentd-gcp:1.18
          env:
            - name: FLUENTD_ARGS
              value: -q
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: home
          gcePersistentDisk:
            pdName: datalab-disk
            fsType: ext4
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
