apiVersion: v1
kind: ReplicationController
metadata:
  name: resilio-rc
  labels:
    server: prod
    app: resilio-rc
spec:
  replicas: 1
  selector:
    server: prod
    app: resilio
  template:
    metadata:
      labels:
        server: prod
        app: resilio
    spec:
      containers:
        - name: resilio
          image: resilio/sync
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              hostPort: 8887
            - containerPort: 5555
              hostPort: 5555
          volumeMounts:
            - name: resilio-disk
              mountPath: /mnt/sync
      volumes:
        - name: resilio-disk
          gcePersistentDisk:
            pdName: resilio
            fsType: ext4
